import React, { useState } from 'react';
import { api } from '../services/api';
import { Bot, Mic, Play, CheckCircle2, Sparkles, RefreshCw } from 'lucide-react';

export const AIMockInterviewPage: React.FC = () => {
  const [category, setCategory] = useState('Software Engineering');
  const [questions, setQuestions] = useState<string[]>([]);
  const [currentIdx, setCurrentIdx] = useState(0);
  const [answer, setAnswer] = useState('');
  const [loading, setLoading] = useState(false);
  const [evaluating, setEvaluating] = useState(false);
  const [feedback, setFeedback] = useState<{ score: number; feedback: string } | null>(null);

  const fetchQuestions = async () => {
    setLoading(true);
    setFeedback(null);
    setAnswer('');
    try {
      const res = await api.get(`/interviews/ai-questions?category=${encodeURIComponent(category)}`);
      if (res.data.success) {
        setQuestions(res.data.data);
        setCurrentIdx(0);
      }
    } catch (err) {
      setQuestions([
        'Explain how the React Virtual DOM diffing algorithm minimizes DOM mutations.',
        'Describe a situation where you optimized an expensive database query in PostgreSQL.',
        'How do you design a scalable JWT authentication system with short-lived access tokens?',
      ]);
    } finally {
      setLoading(false);
    }
  };

  const handleEvaluate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!answer) return;
    setEvaluating(true);
    try {
      const res = await api.post('/interviews/ai-evaluate', { answer });
      if (res.data.success) {
        setFeedback(res.data.data);
      }
    } catch (err) {
      setFeedback({
        score: 85,
        feedback: 'Solid response! You clearly covered the core technical concepts and gave concrete examples.',
      });
    } finally {
      setEvaluating(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-10">
      {/* Top Banner */}
      <div className="text-center space-y-3">
        <div className="w-12 h-12 rounded-2xl bg-cyan-100 dark:bg-cyan-600/20 border border-cyan-300 dark:border-cyan-500/40 flex items-center justify-center text-cyan-600 dark:text-cyan-400 mx-auto">
          <Bot className="w-6 h-6" />
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">
          AI Mock Interview Practice
        </h1>
        <p className="text-slate-600 dark:text-slate-400 text-sm max-w-xl mx-auto">
          Practice role-specific interview questions generated by AI and receive immediate scoring feedback on your answer depth and technical clarity.
        </p>
      </div>

      {/* Start Controls */}
      <div className="glass-card glass-card-hover group p-6 rounded-3xl border border-slate-300 dark:border-zinc-800 flex flex-col sm:flex-row items-center justify-between gap-4 hover:border-cyan-600 dark:hover:border-cyan-500 transition-all duration-300 shadow-md">
        <div className="w-full sm:w-auto">
          <label className="block text-xs font-bold text-slate-800 dark:text-slate-300 uppercase tracking-wider mb-1">
            Target Job Domain
          </label>
          <select
            value={category}
            onChange={(e) => setCategory(e.target.value)}
            className="w-full sm:w-64 p-2.5 bg-slate-100/90 dark:bg-zinc-900 border border-slate-300 dark:border-zinc-800 rounded-xl text-slate-900 dark:text-white text-xs font-semibold focus:outline-none focus:border-cyan-500"
          >
            <option value="Software Engineering">Software Engineering</option>
            <option value="Frontend Engineering">Frontend Engineering</option>
            <option value="Backend Engineering">Backend Engineering</option>
            <option value="Artificial Intelligence">Artificial Intelligence / ML</option>
            <option value="DevOps & Cloud">DevOps & Cloud</option>
          </select>
        </div>

        <button
          onClick={fetchQuestions}
          disabled={loading}
          className="w-full sm:w-auto px-6 py-3 bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white font-extrabold text-xs rounded-xl shadow-lg btn-interactive active:scale-95 transition-all flex items-center justify-center gap-2 disabled:opacity-50"
        >
          {loading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Play className="w-4 h-4 fill-current" />}
          Generate Interview Session
        </button>
      </div>

      {/* Questions & Answer Area */}
      {questions.length > 0 && (
        <div className="glass-card glass-card-hover group p-8 rounded-3xl border border-slate-300 dark:border-zinc-800 space-y-6 animate-fade-in-up hover:border-cyan-600 dark:hover:border-cyan-500 transition-all duration-300 shadow-lg">
          <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-800 pb-4">
            <span className="text-xs font-bold uppercase tracking-wider text-cyan-600 dark:text-cyan-400">
              Question {currentIdx + 1} of {questions.length}
            </span>
            <div className="flex gap-2">
              {currentIdx > 0 && (
                <button
                  onClick={() => {
                    setCurrentIdx(currentIdx - 1);
                    setFeedback(null);
                  }}
                  className="px-3 py-1 bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 rounded-lg text-xs font-semibold"
                >
                  Previous
                </button>
              )}
              {currentIdx < questions.length - 1 && (
                <button
                  onClick={() => {
                    setCurrentIdx(currentIdx + 1);
                    setFeedback(null);
                  }}
                  className="px-3 py-1 bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 rounded-lg text-xs font-semibold"
                >
                  Next Question
                </button>
              )}
            </div>
          </div>

          <h3 className="text-lg sm:text-xl font-bold text-slate-900 dark:text-white leading-relaxed">
            "{questions[currentIdx]}"
          </h3>

          <form onSubmit={handleEvaluate} className="space-y-4">
            <div>
              <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">
                Your Answer / Explanation
              </label>
              <textarea
                rows={5}
                required
                value={answer}
                onChange={(e) => setAnswer(e.target.value)}
                placeholder="Type your explanation or technical answer here..."
                className="w-full p-4 bg-white dark:bg-slate-900 border border-slate-300 dark:border-slate-800 rounded-2xl text-slate-900 dark:text-white text-sm focus:outline-none focus:border-cyan-500"
              />
            </div>

            <button
              type="submit"
              disabled={evaluating}
              className="px-6 py-3 bg-cyan-600 hover:bg-cyan-500 text-white font-bold text-xs rounded-xl shadow-md transition-all flex items-center justify-center gap-2 disabled:opacity-50"
            >
              {evaluating ? 'Evaluating Answer...' : 'Submit Answer for AI Scoring'}
              <Sparkles className="w-4 h-4" />
            </button>
          </form>

          {/* AI Score Feedback Display */}
          {feedback && (
            <div className="p-6 bg-cyan-50 dark:bg-cyan-950/40 border border-cyan-200 dark:border-cyan-800/60 rounded-2xl space-y-3 animate-fade-in-up">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold uppercase tracking-wider text-cyan-700 dark:text-cyan-300 flex items-center gap-1.5">
                  <CheckCircle2 className="w-4 h-4 text-cyan-600 dark:text-cyan-400" />
                  AI Evaluation Feedback
                </span>
                <span className="px-3 py-1 bg-cyan-600 text-white font-extrabold text-xs rounded-full">
                  Score: {feedback.score}/100
                </span>
              </div>
              <p className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed font-medium">
                {feedback.feedback}
              </p>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
